export let defaultFormData ={
    age_nearest_bday: 20,
    gender: 'male',
    marital_status: 'single',
    nationality: 'Sri Lankan',
    country: 'Sri Lanka',
    district: 'Gampaha',
    city: 'Negombo',
    occupation: 'Graphic Designer',
    employment_type: 'Contract',
    designation: 'Junior Designer',
    hazardous_level: 'Low',
    hazardous_activities: '',
    monthly_income: 140000,
    existing_insurance: 'No',
    dependents_count: 4,
    primary_goal: 'Cheap & quick',
    secondary_goal: 'None',
    chronic_disease: false,
    cardiovascular_health_issue: false,
    cancer_or_tumors: false,
    respiratory_conditions: false,
    neurological_or_mental_health_conditions: false,
    gastrointestinal_conditions: false,
    musculoskeletal_conditions: false,
    infectious_or_sexual_health_conditions: false,
    recent_treatment_or_surgery: false,
    covid19_related_conditions: false,
    bmi: 22.5,
    smoker: 'No',
    alcohol_consumer: 'No',
    travel_history_high_risk_countries: false,
    dual_citizenship: false,
    tax_or_regulatory_flags: false,
    insurance_history_issues: false,
    current_insurance_status: 'None',
    employer_scheme: false,
  }